### ISSUE TITLE
Minecraft Server Crashes

### ISSUE THREAD

**Issue by chemcodex** [Quplet/FixedVillagerTrades#1]
[latest.log](https://github.com/Quplet/FixedVillagerTrades/files/9035396/latest.log)

its a fabric server with carpet and so on, the mod list is in there

also, i see config nowhere. no config file,not showing up in modmenu

**Comment by Quplet** [comment]
A couple things.

1. The Fixed Villager Trades version is listed as 1.0.0, not 1.1.0. Didn't you say 1.0.0 worked and 1.1.0 didn't?

2. It's a watchdog error, and nothing in the stack trace seems to point back to my mod or really any mod. Does this consistently happen, or randomly?

**Comment by chemcodex** [comment]
sorry, i pasted wrong log there, its now replaced.

**Comment by Quplet** [comment]
Alright I see the issue. I'll work on a fix once I get home.
